/**
 * @(#)LSessionImpl.java
 * Copyright (C) 2001 Vasili Gavrilov
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.is.jms;

import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageListener;

/**
 * Lightweight not threaded session working with javax.jms.Message.<p>
 * Delegates message distribution to concrete message broker implementation
 * (socket, http etc). Not threaded - messages supposed to be retrieved by the
 * user class. For threaded callbacking version look into LSessionRunnableImpl.
 * Represents an active session (connected user for example).
 * If there is a container for this class, it's that container's responsibility -
 * to generate uid (pk) for Session objects. (check of already existing
 * Sessions may be needed for example)<p>
 * This class makes caching of the hashcode for efficient
 * working with Hashtables.
 *
 * @version 1.1
 * @since jdk1.0
 */
public class LSessionImpl extends org.is.structures.Identity implements /*javax.jms.Session, Serializable*/MessagePortal{ //we support JDK1.0 on the client

  /**
   * Concrete implementation of message transport
   */
  private transient MessagePortal msgTransport;

  /**
   * Default constructor. Notice: this constructor does not generates uid (primary
   * key) for this object (unique in the JVM). When this Session will be added to
   * a container, containing other sessions, uid will be generated by that container
   * (since uid depends on other sessions or application specific, so there is
   * need to look for other Session objects to verify that uid is unique for sure)
   */
  public LSessionImpl(){

    super();
  }

  public LSessionImpl(String pk){

    super(pk);
  }

  /**
   * Creates new MessageImpl instance
   */
  public Message createMessage() throws JMSException{

    Message msg=new MessageImpl();
    return msg;
  }

  /**
   * Delegates connect to concrete implementation of transport.
   * If transport has not been set - JMSException is thrown
   */
  public void connect() throws JMSException{

    if(msgTransport==null){
      //throw new JMSException("LSessionImpl::message transport is not set");
      
    }
    msgTransport.connect();
  }

  public void sendMessage(Message msg) throws JMSException{

    msgTransport.sendMessage(msg);
  }

  public Message getMessage() throws JMSException{

    return msgTransport.getMessage();
  }

  /**
   * Delegates close to concrete implementation of transport.
   */
  public void close() throws JMSException{

    msgTransport.close();
  }

  /**
   * Sets new ID for this session
   */
  public void setSessionID(String sessionID){

    setPK(sessionID);
  }

  /**
   * Returns ID for this session
   */
  public String getSessionID(){

    return getPK();
  }

  /**
   * Sets message transport for this session
   */
  public void setMessageTransport(MessagePortal mt){

    msgTransport=mt;
  }

}




