/**
 * @(#)LSessionRunnableImpl.java
 * Copyright (C) 2001 Vasili Gavrilov
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.is.jms;

import javax.jms.JMSException;
import javax.jms.ExceptionListener;
import javax.jms.Message;
import javax.jms.MessageListener;

/**
 * Lightweight analog of SessionImpl (not implementing javax.jms.Session fully)
 * for small applets (agents) working only with javax.jms.Message.
 * Delegates message distribution to concrete message broker implementation
 * (socket, http etc). Extends LSessionImpl adding Thread getting messages
 * and making callbacks to listeners.
 *
 * @see LSessionImpl
 * @version 1.1
 * @since jdk1.0
 */
public class LSessionRunnableImpl extends LSessionImpl implements Runnable{

  private MessageListener listener;
  private ExceptionListener eListener;
  private Thread worker;
  private long timeout=40; //time to wait between Message deliveries (to be a good citizen)

  /**
   * Default constructor. Notice: this constructor does not generates uid (primary
   * key) for this object (unique in the JVM). When this Session will be added to
   * a container, containing other sessions, uid will be generated by that container
   * (since uid depends on other sessions or application specific, so there is
   * need to look for other Session objects to verify that uid is unique for sure)
   */
  public LSessionRunnableImpl(){

    super();
  }

  /**
   * Constructor taking UID as unique key of the session (if this Session will
   * be stored in a Hashtable)
   */
  public LSessionRunnableImpl(String pk){

    super(pk);
  }

  /**
   * Returns MessageListener if registered one
   */
  public MessageListener getMessageListener(){

     return listener;
  }

  /**
   * Sets MessageListener this class calling back to (on Message arrivals)
   */
  public void setMessageListener(MessageListener listener){
  
     this.listener=listener;
  }

  /**
   * Returns ExceptionListener if registered one
   */
  public ExceptionListener getExceptionListener(){

     return eListener;
  }

  /**
   * Sets ExceptionListener this class calling back to (in the case of
   * connection loss for example)
   */
  public void setExceptionListener(ExceptionListener l){

     eListener=l;
  }

  /**
   * Starts thread reading messages and delivering it to the message listener
   */
  public synchronized void start(){

    if(worker==null){
       worker=new Thread(this);
       worker.setDaemon(true);
       worker.start();
    }
  }

  /**
   * Frees resources. Stops thread delivering messages (in this class) and calling
   * super's close() method.
   */
  public synchronized void close() throws JMSException{

    if(worker!=null){
       worker.stop();
       worker=null;
    }

    super.close();
  }

  /**
   * Sets timeout in milliseconds to wait between message deliveries 
   */
  public void setTimeout(long t){

    timeout=t;
  }

  /**
   * Gets timeout in milliseconds to wait between message deliveries
   */
  public long getTimeout(){

    return timeout;
  }

  /**
   * This thread's body (delivering messages to message listener)
   */
  public void run(){

     if(listener==null){
        System.out.println("LSessionRunnableImpl::MessageLestener is null: exiting from Session thread");
        return;
     }

     try{
        while(true){

          Message msg=getMessage();
          listener.onMessage(msg);

          try{Thread.sleep(timeout);}catch(InterruptedException e){}
        }
      }
      catch(JMSException e){

         if(eListener!=null){
            eListener.onException(e);
         }
         else{
            //no Exception listeners - print at least to the console
            System.err.println(e);
         }

      }

  }

}




