ArchiveType=2
OutputFile=C:\\JBuilder3\\myprojects\\ljms\\common\\examples\\trivialChat\\chat.jar
ManifestFile=<auto generate>
ExtractManifest=false
DisabledNodeKeys=1
DisabledNodes0=file:///C:\\JBuilder3\\myprojects\\ljms\\common\\examples\\trivialChat\\index.html;
ExtraClassKeys=0
ExtraFileKeys=0
ExcludedDirKeys=0
ExcludedClassKeys=0
ExcludedFileKeys=0
