/**
 * @(#)Client.java
 * Copyright (C) 2001 Vasili Gavrilov
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.is.structures;

import java.util.Properties;
import java.util.Enumeration;

/**
 * Object representing a client (not persistent client, connected currently --
 * this class extends Session)
 * Not used in current version: org.is.jms.LSessionImpl used instead
 *
 * @see Session
 * @since jdk1.0
 */
public class Client extends Identity{

  private Properties props = new Properties();
  private Queue mq=new Queue();

  /**
   * Default constructor. Notice: this constructor does not generates uid (primary
   * key) for this object. When this Client will be added to a container, containing
   * other Clients, uid will be generated by that container (since uid depends
   * on other sessions or application specific, so there is need to look for other
   * Session objects to verify that uid is unique for sure)
   */
  public Client(){

     super();
  }

  public Properties getProperties(){

    return props;
  }

  public void setProperties(Properties props){

    this.props=props;
  }

  public String getProperty(String key){

    return props.getProperty(key);
  }

  public Enumeration getPropertyNames(){

    return props.keys();
  }

  public void addProperty(String key, String value){

    props.put(key, value);
  }

  /**
   * Adds the message for this client
   */
  public void addMessage(Object m){

     mq.push(m);
  }

  /**
   * Returns the next message for this client
   */
  public Object getNextMessage(){

     //the thread reading messages will be blocked here:
     return mq.pull();
  }  

  /**
   * For debugging purposes only
   */
  public String toString(){

      StringBuffer sb=new StringBuffer();
      for(Enumeration enum = props.propertyNames(); enum.hasMoreElements() ;) {
          String aKey=(String)enum.nextElement();
          String aValue=props.getProperty(aKey);
          sb.append(aKey);
          sb.append('=');
          sb.append(aValue);
          if(enum.hasMoreElements())sb.append(" ");
      }
		  return sb.toString();
  }

}




