/**
 * DebugLevel. For currently available debug levels names look into DebugLevel class.
 * Names are like:
 * DEBUG_NONE
 * DEBUG_ALL
 * DEBUG_BRIEF 
 * DEBUG_XML_PARSER
 * DEBUG_NOT_SPECIFIED
 * DEBUG_PROCESSOR
 * DEBUG_LRU_CACHE
 * SHOW_CACHE_IN_WORK
 * DEBUG_ALL_THREADS_DUMP
 * DEBUG_THREADS_DUMP
 *
 * For current updated list consult with org.is.logmanager.DebugLevel.java
 */
debug_level=DEBUG_BRIEF

logs.print_stack_trace=true

logs.rotate=true

logs.max_size=500000