-- LJMS queue table, Oracle 12c+.
-- Use Dialect.ORACLE.

CREATE TABLE QUEUE (
  id          NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
  task_type   VARCHAR2(32)   NOT NULL,          -- what kind of work
  ref_id      NUMBER(19),                       -- a row id in your own tables
  payload     CLOB,                             -- anything else the task needs
  status      VARCHAR2(16)   DEFAULT 'NEW' NOT NULL,
  not_before  TIMESTAMP,                        -- run no earlier than
  owner       VARCHAR2(128),                    -- node + JVM incarnation
  owner_node  VARCHAR2(64),                     -- node alone
  lease_until TIMESTAMP,                        -- this claim expires at
  error       VARCHAR2(1000),
  created     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  started     TIMESTAMP,
  finished    TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX ix_queue_take  ON QUEUE (status, id);            -- the head-of-queue read
CREATE INDEX ix_queue_lease ON QUEUE (status, lease_until);   -- recovery sweep
CREATE INDEX ix_queue_node  ON QUEUE (status, owner_node);    -- restart-is-the-retry sweep

-- Note on generated keys: the Oracle JDBC driver wants the key column named,
-- so if you use Oracle, change the one call in QueueDAO.put() from
--   con.prepareStatement(q, Statement.RETURN_GENERATED_KEYS)
-- to
--   con.prepareStatement(q, new String[] { "id" })
