-- LJMS queue table, PostgreSQL 12+.
-- Use Dialect.POSTGRES.

CREATE TABLE QUEUE (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  task_type   VARCHAR(32)  NOT NULL,            -- what kind of work
  ref_id      BIGINT           NULL,            -- a row id in your own tables
  payload     TEXT             NULL,            -- anything else the task needs
  status      VARCHAR(16)  NOT NULL DEFAULT 'NEW',
  attempts    INT          NOT NULL DEFAULT 0,   -- times claimed; diagnostics
  not_before  TIMESTAMP        NULL,            -- run no earlier than
  owner       VARCHAR(128)     NULL,            -- node + JVM incarnation
  owner_node  VARCHAR(64)      NULL,            -- node alone
  lease_until TIMESTAMP        NULL,            -- this claim expires at
  error       VARCHAR(1000)    NULL,
  created     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started     TIMESTAMP        NULL,
  finished    TIMESTAMP        NULL,
  PRIMARY KEY (id)
);

CREATE INDEX ix_queue_take  ON QUEUE (status, id);            -- the head-of-queue read
CREATE INDEX ix_queue_lease ON QUEUE (status, lease_until);   -- recovery sweep
CREATE INDEX ix_queue_node  ON QUEUE (status, owner_node);    -- restart-is-the-retry sweep
